from django.urls import path, include, re_path
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render, get_object_or_404
from django.views.static import serve
from manager import views as mviews




urlpatterns = [    
          path("manager/signup",mviews.managersignup,name='manager_signup'),
      url("manager/login", mviews.managerlookup, name='manager_login'),
        #   url("manager/new/accounts/signup", mviews.managersignup, name='manager_new_account_signup'),
      url("manager/accounts/auth/", mviews.loginuser, name='manager_account_auth'),

    path('manager/', mviews.index, name='manager_index'),
    path('manager/dashboard', mviews.dashboard.as_view(), name='manager_dashboard'),
    path('manager/app', mviews.app, name='manager_app'),
    path('manager/store_setup', mviews.storesetup, name='manager_store_setup'),
    path('manager/slideshows', mviews.slideshows, name='manager_slideshows'),
    path('manager/add_product', mviews.addproduct, name='manager_add_product'),

    path('manager/my/order/<str:orderid>', mviews.myorder, name='manager_my_order'),
    path('manager/download_order/<str:orderid>', mviews.downloadorder, name='manager_download_order'),
    path('manager/remove_order/<str:orderid>', mviews.remove_order, name='manager_remove_order'),
    path('manager/overview', mviews.overview, name='manager_overview'),
    path('manager/checkout', mviews.checkout, name='manager_checkout'),
    path('manager/orders/<str:filter>', mviews.orders, name='manager_orders'),
    path('manager/order/<str:orderid>', mviews.order, name='manager_order'),
    path('manager/orders_page', mviews.orderspage, name='manager_orders_page'),
    path('manager/action/product_image/<str:productid>', mviews.addproductimage, name='manager_add_product_image'),
    path('manager/action/product_variation/<str:productid>', mviews.addproductvariation, name='manager_add_product_variation'),
    path('manager/product_overview/<str:productid>', mviews.product_overview, name='manager_product_overview'),
    path('manager/product/<str:productid>/<str:variationid>', mviews.editproductvariation, name='manager_edit_product_variation'),
    path('manager/product/<str:productid>/edit', mviews.editproduct, name='manager_edit_product'),
    path('manager/product/<str:productid>/information/edit', mviews.editproductinformation, name='manager_edit_product_information'),
    path('manager/product_variations/<str:productid>', mviews.product_variations, name='manager_product_variations'),
    path('manager/products', mviews.products, name='manager_products'),
    path('manager/product/<str:productid>', mviews.product, name='manager_product'),
    path('manager/product_information/<str:productid>', mviews.product_information, name='manager_product_information'),
    path('manager/product_images/<str:productid>', mviews.product_images, name='manager_product_images'),
    path('manager/products_page', mviews.productspage, name='manager_products_page'),
    path('manager/error_500', mviews.error500page, name='manager_error_500'),
    path('manager/error_404', mviews.error404page, name='manager_error_404'),
    path('manager/monthly_graph', mviews.monthlysalesgraph, name='manager_monthly_graph'),
    path('manager/product_monthly_graph/<str:productid>', mviews.productmonthlysalesgraph, name='manager_product_monthly_graph'),
    path('manager/carted_product/<str:id>', mviews.cartedproduct, name='manager_carted_product'),
    path('manager/new_products', mviews.newproducts, name='manager_new_products'),
    path('manager/pay_on_delivery/<str:orderid>', mviews.payondelivery, name='manager_pay_on_delivery'),
    path('manager/remove_from_cart/<str:id>', mviews.remove_from_cart, name='manager_remove_carted_product'),
    path('manager/home_group/<str:id>', mviews.homegroupproducts, name='manager_home_group_products'),
    path('manager/flashsale/all/products/<str:id>', mviews.allflashsaleproducts, name='all_manager_flash_sales_products'),
    path('manager/flash_sales_products/<str:id>', mviews.flashsaleproducts, name='manager_flash_sales_products'),
    path('manager/flashsale/<str:id>', mviews.flashsalespage, name='manager_flash_sales_page'),
    path('manager/brand/<str:slug>', mviews.brandpage, name='manager_brand_page'),
    path('manager/brand/products/<str:slug>', mviews.brandproducts, name='manager_brand_products'),
    path('manager/slideshow/<str:slug>', mviews.slideshowpage, name='manager_slideshow_page'),
    path('manager/slideshow/products/<str:slug>', mviews.slideshowproducts, name='manager_slideshow_products'),
    path('manager/flash_sales_product/<str:id>', mviews.flashsaleproduct, name='manager_flash_sales_product'),
    path('manager/product/<str:id>', mviews.product, name='manager_product'),
    path('manager/product_details/<str:productid>', mviews.product_details, name='manager_product_details'),
    path('manager/order_details/<str:orderid>', mviews.order_details, name='manager_order_details'),
    path('manager/add_to_cart/<str:productid>', mviews.add_to_cart, name='manager_add_to_cart'),
    path('manager/add_variation_to_cart/', mviews.add_variation_to_cart, name='manager_add_variation_to_cart'),
    path('manager/settings/', mviews.settings, name='manager_settings'),
    path('manager/store_information/', mviews.store_information, name='manager_store_information'),
    path('manager/store_branding/', mviews.store_branding, name='manager_store_branding'),
    path('manager/store_payment/', mviews.store_payment, name='manager_store_payment'),
    path('manager/edit/store_branding/', mviews.editstorebranding, name='manager_edit_store_branding'),
    path('manager/edit/store_information/', mviews.editstoreinformation, name='manager_edit_store_information'),
    path('manager/edit/store_payment/', mviews.editstorepayment, name='manager_edit_store_payment'),
    path('manager/store_socials/', mviews.store_socials, name='manager_store_socials'),
    path('manager/store_measurement_units/', mviews.store_measurement_units, name='manager_store_measurement_units'),
    path('manager/add_store_social_link/', mviews.addsocialink, name='manager_add_store_social_link'),
    path('manager/add_measurement_unit/', mviews.addmeasurementunit, name='manager_add_measurement_unit'),
    path('manager/similiar_products/<str:productid>', mviews.similarproducts, name='manager_similar_products'),
    path('manager/add_to_saved/<str:productid>', mviews.add_to_saved, name='manager_add_to_saved'),
    path('manager/remove_from_saved/<str:productid>', mviews.remove_from_saved, name='manager_remove_from_saved'),
    path('manager/category/<str:name>', mviews.categorys, name='manager_our_offers'),
    path('manager/offer_products/<str:name>', mviews.categoryproducts, name='manager_offer_products'),
    path('manager/category/<str:name>', mviews.categorys, name='manager_our_categorys'),
    path('manager/group/<str:slug>', mviews.homegroup, name='manager_home_group'),
    path('manager/group/products/<str:slug>', mviews.allhomegroupproducts, name='all_manager_home_group_products'),
    path('manager/group/all/', mviews.allhomegroupsection, name='all_manager_home_group_sections'),
    path('manager/newsletter/subscribe/', mviews.newlettersubscription, name='manager_news_letter_subscription'),
    path('manager/brand/<str:name>', mviews.categorys, name='manager_brands'),
    path('manager/category_products/<str:name>', mviews.categoryproducts, name='manager_category_products'),
    path('manager/update_cart/', mviews.update_cart, name='manager_update_cart'),
    path('manager/cart_count/', mviews.cart_count, name='manager_cart_count'),
    path('manager/products/all', mviews.allproducts, name='manager_all_products'),
    path('manager/products/page/all', mviews.allproductspage, name='manager_all_products_page'),
    path('manager/products/paginated', mviews.paginatedproducts, name='manager_paginated_products'),
    path('manager/products_you_may_like/', mviews.products_you_may_like, name='manager_products_you_may_like'),
    path('manager/saved_items/', mviews.saveditemspage, name='manager_saved_items_page'),
    path('manager/saved_items/products', mviews.savedproducts, name='manager_saved_items_products'),
    path('manager/search/', mviews.search_products, name='manager_search_products'),
    path('manager/place_order/', mviews.place_order, name='manager_place_order'),
    path('manager/my_orders/', mviews.myorders, name='manager_my_orders'),

    path('manager/cart/', mviews.cart, name='manager_cart'),
    path('manager/update_contact_details/', mviews.updatecontactdetails, name='manager_update_contact_details'),
    path('manager/order_paid', mviews.orderpaid, name='manager_order_paid'),
    path('manager/verify_payment', mviews.verifypayment, name='manager_verify_payment'),
    url("manager/logout", mviews.logoutuser, name='manager_account_logout'),

    # url(r'^account_activation_sent/$', gviews.account_activation_sent,
    #     name='manager_account_activation_sent'),
    # url(r'^accounts/', include('allauth.urls')),
    # url('activate-account', gviews.activate, name='manager_activate_account'),
    # url('createwallet', gviews.createaccounts, name='manager_create_accounts'),
    # url('resendactivationcode', gviews.resendactivationcode,
    #     name='manager_resend_activation_code'),
    # url('unsuspend', gviews.unsuspend, name='manager_unsuspend'),
    path('manager/select_account_type/', mviews.select_account_type, name='manager_select_account_type'),
    path('manager/confirmemail', mviews.confirmemail, name='manager_confirm_email'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
