# Generated by Django 3.2.10 on 1980-01-01 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Platform Name', max_length=255)),
                ('color', models.CharField(blank=True, default='short description', max_length=1000)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('date_time_added', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='')),
            ],
            options={
                'db_table': 'platform_social_links',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='store Name', max_length=255)),
                ('store_name_prefix', models.CharField(default='store Name Prefix', max_length=255)),
                ('logo', models.ImageField(default='', upload_to='')),
                ('logo_loader', models.ImageField(blank=True, default='', upload_to='')),
                ('logo_loader_text', models.ImageField(blank=True, default='', upload_to='')),
                ('payment_cards_image', models.ImageField(blank=True, default='', upload_to='')),
                ('error_404_background', models.ImageField(blank=True, default='', upload_to='')),
                ('error_500_background', models.ImageField(blank=True, default='', upload_to='')),
                ('logo_icon', models.ImageField(blank=True, default='', upload_to='')),
                ('phone_number', models.CharField(blank=True, default='', max_length=13)),
                ('phone_number_2', models.CharField(blank=True, default='', max_length=13)),
                ('address', models.CharField(blank=True, default='', max_length=1000)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('call_code', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('street_number', models.CharField(default='', max_length=225)),
                ('street', models.CharField(default='', max_length=225)),
                ('city', models.CharField(default='', max_length=225)),
                ('country', django_countries.fields.CountryField(default='', max_length=2)),
                ('state', models.CharField(default='', max_length=225)),
                ('full_address', models.CharField(blank=True, default='', max_length=500)),
                ('city_code', models.CharField(blank=True, default='', max_length=45, null=True)),
                ('country_code', models.CharField(blank=True, default='', max_length=45, null=True)),
                ('primary_color', models.CharField(default='chartreuse', max_length=255)),
                ('background_color', models.CharField(default='chartreuse', max_length=255)),
                ('footer_color', models.CharField(choices=[('white', 'White'), ('lighter', 'Light'), ('dark', 'Dark')], default='dark', max_length=255)),
                ('payment_manager', models.CharField(blank=True, choices=[('platform', 'Platform'), ('custom', 'Custom')], default='platform', max_length=100)),
                ('payment_processor', models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='paystack', max_length=100)),
                ('theme', models.CharField(blank=True, choices=[('simple', 'Simple'), ('functional', 'Functional')], default='simple', max_length=100)),
                ('payment_options', models.CharField(blank=True, choices=[('both', 'Both'), ('on', 'Online'), ('od', 'On delivery')], default='both', max_length=100)),
                ('is_ready', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Setting',
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
