# Generated by Django 3.2.10 on 1980-01-01 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.TextField(blank=True, default='', max_length=500)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('formatted_quantity', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('formatted_amount', models.CharField(blank=True, default='', max_length=100)),
                ('cartedproductid', models.CharField(blank=True, default='', max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('pickedup', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('ordered', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('date_time_paid', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date_time_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cartedproducts',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=550)),
                ('transaction_pin', models.CharField(blank=True, default='', max_length=5)),
                ('savings_rating', models.IntegerField(default=0)),
                ('credit_rating', models.IntegerField(default=5)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=225)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(blank=True, upload_to='media/customers/photo')),
                ('customerid', models.CharField(blank=True, default='', editable=False, max_length=255)),
                ('profile_edit_date', models.DateField(auto_now=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('date_time_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('secret_question', models.CharField(blank=True, default='', max_length=225)),
                ('secret_answer', models.CharField(blank=True, default='', max_length=225)),
                ('previous_email', models.CharField(blank=True, default='', max_length=225)),
                ('last_token', models.CharField(blank=True, default='', max_length=225)),
                ('profile_updated', models.BooleanField(default=False)),
                ('suspension_count', models.IntegerField(default=0)),
                ('briefly_suspended', models.BooleanField(default=False)),
                ('time_suspended', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('time_suspended_timestamp', models.IntegerField(blank=True, default=0)),
                ('reference_code', models.CharField(blank=True, default='', max_length=225)),
                ('street_number', models.CharField(default='', max_length=225)),
                ('street', models.CharField(default='', max_length=225)),
                ('landmark', models.CharField(blank=True, default='', max_length=225)),
                ('nearest_bus_stop', models.CharField(blank=True, default='', max_length=225)),
                ('city', models.CharField(default='', max_length=225)),
                ('lga', models.CharField(blank=True, default='', max_length=225)),
                ('country', django_countries.fields.CountryField(default='', max_length=2)),
                ('state', models.CharField(default='', max_length=225)),
                ('full_address', models.CharField(blank=True, default='', max_length=500)),
                ('currency', models.CharField(blank=True, choices=[('NGN', 'Naira'), ('USD', 'Dollar'), ('GBP', 'Pounds'), ('EUR', 'Euro')], default='', max_length=500)),
                ('temporary_password', models.BooleanField(default=False)),
                ('middle_name', models.CharField(blank=True, default='', max_length=45)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('call_code', models.CharField(blank=True, default='', max_length=5)),
                ('phone_number_1', models.CharField(blank=True, default='', max_length=45)),
                ('phone_number_2', models.CharField(blank=True, default='', max_length=45)),
                ('address1', models.CharField(blank=True, default='', max_length=200)),
                ('address2', models.CharField(blank=True, default='', max_length=200)),
                ('city_code', models.CharField(blank=True, default='', max_length=45)),
                ('country_code', models.CharField(blank=True, default='', max_length=45)),
                ('del_flg', models.BooleanField(default=False)),
                ('transaction_pin_set', models.BooleanField(default=False)),
                ('privacy_terms_accepted', models.BooleanField(default=False)),
                ('bvn_verified', models.BooleanField(default=False)),
                ('business_mode', models.BooleanField(default=False)),
                ('loansecure_accepted', models.BooleanField(default=False)),
                ('can_withdraw', models.BooleanField(default=False)),
                ('can_transfer', models.BooleanField(default=False)),
                ('contact_ready', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('formatted_price', models.CharField(blank=True, default='', max_length=100)),
                ('locationid', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'deliverylocations',
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'measurementunits',
            },
        ),
        migrations.CreateModel(
            name='NewsLetterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('date_time_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'newslettersubscriptions',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='products/photo')),
                ('description', tinymce.models.HTMLField(blank=True, default='')),
                ('weight', models.FloatField(blank=True, default=0)),
                ('discount', models.IntegerField(blank=True, default=0)),
                ('discount_price', models.IntegerField(blank=True, default=0)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('effective_price', models.IntegerField(blank=True, default=0)),
                ('available_stock', models.IntegerField(blank=True, default=0)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('purchase_count', models.IntegerField(blank=True, default=0)),
                ('date_time_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_count', models.IntegerField(blank=True, default=0)),
                ('formatted_price', models.CharField(blank=True, default='', max_length=100)),
                ('formatted_discount_price', models.CharField(blank=True, default='', max_length=100)),
                ('formatted_effective_price', models.CharField(blank=True, default='', max_length=100)),
                ('productid', models.CharField(blank=True, default='', max_length=100)),
                ('best_deal', models.BooleanField(default=False)),
                ('special_package', models.BooleanField(default=False)),
                ('url', models.TextField(blank=True, default='')),
                ('measurement_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.measurementunit')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='VisitorsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_1', models.TextField(default='', max_length=200)),
                ('ip_2', models.TextField(default='', max_length=200)),
                ('ip_3', models.TextField(default='', max_length=200)),
                ('host_name', models.TextField(default='', max_length=200)),
                ('url', models.URLField()),
                ('date_time_added', models.DateTimeField(auto_now=True)),
                ('customerid', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.TextField(blank=True, default='', max_length=1000)),
            ],
            options={
                'db_table': 'visitorslog',
            },
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/slideshows/photo')),
                ('description', tinymce.models.HTMLField(blank=True, default='')),
                ('price', models.IntegerField(blank=True, default=0)),
                ('formatted_price', models.CharField(blank=True, default='', max_length=100)),
                ('productid', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(blank=True, default='')),
                ('products', models.ManyToManyField(blank=True, default='', to='app.Product')),
            ],
            options={
                'db_table': 'slideshows',
            },
        ),
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.TextField(max_length=500)),
                ('saveid', models.CharField(blank=True, default='', max_length=100)),
                ('date_time_added', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('products', models.ManyToManyField(blank=True, default='', to='app.Product')),
            ],
            options={
                'db_table': 'savedproducts',
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/best_deals/photo')),
                ('description', tinymce.models.HTMLField(blank=True, default='')),
                ('price', models.IntegerField(blank=True, default=0)),
                ('discount', models.IntegerField(blank=True, default=0)),
                ('discount_price', models.IntegerField(blank=True, default=0)),
                ('weight', models.FloatField(blank=True, default=0)),
                ('purchase_count', models.IntegerField(blank=True, default=0)),
                ('formatted_price', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.TextField(blank=True, default='')),
                ('available_stock', models.IntegerField(blank=True, default=0)),
                ('productid', models.CharField(blank=True, default='', max_length=100)),
                ('measurement_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.measurementunit')),
            ],
            options={
                'db_table': 'productvariations',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/best_deals/photo')),
                ('flip', models.BooleanField(default=False)),
                ('url', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'db_table': 'productimages',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', to='app.Tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.ManyToManyField(blank=True, default='', to='app.ProductVariation'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.TextField(max_length=500)),
                ('total', models.IntegerField(blank=True, default=0)),
                ('formatted_total', models.CharField(blank=True, default='', max_length=100)),
                ('orderid', models.CharField(blank=True, default='', max_length=100)),
                ('payment_method', models.CharField(blank=True, choices=[('op', 'op'), ('pd', 'pd')], default='', max_length=100)),
                ('delivery_option', models.CharField(blank=True, choices=[('p', 'p'), ('d', 'd')], default='', max_length=100)),
                ('date_time_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_time_paid', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('paid', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('pickedup', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('delivery_location', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.deliverylocation')),
                ('products', models.ManyToManyField(blank=True, default='', to='app.CartedProduct')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='HomePageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(blank=True, default='')),
                ('header_background_color', models.CharField(default='white', max_length=255)),
                ('header_text_color', models.CharField(default='black', max_length=255)),
                ('index', models.IntegerField(blank=True, default=1)),
                ('products', models.ManyToManyField(blank=True, default='', to='app.Product')),
            ],
            options={
                'db_table': 'homepagegroups',
            },
        ),
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, default=0)),
                ('formatted_price', models.CharField(blank=True, default='', max_length=100)),
                ('discount', models.IntegerField(blank=True, default=0)),
                ('product', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'db_table': 'flashsaleproducts',
            },
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('end_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('start_time_timestamp', models.IntegerField(blank=True, default=0)),
                ('products', models.ManyToManyField(blank=True, default='', to='app.FlashSaleProduct')),
            ],
            options={
                'db_table': 'flashsales',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/product_groups/photo')),
                ('is_top', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('products', models.ManyToManyField(blank=True, default='', to='app.Product')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.AddField(
            model_name='cartedproduct',
            name='customer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AddField(
            model_name='cartedproduct',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='cartedproduct',
            name='variation',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.productvariation'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.TextField(max_length=500)),
                ('total', models.IntegerField(blank=True, default=0)),
                ('formatted_total', models.CharField(blank=True, default='', max_length=100)),
                ('cartid', models.CharField(blank=True, default='', max_length=100)),
                ('date_time_added', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('products', models.ManyToManyField(blank=True, default='', to='app.CartedProduct')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/product_groups/photo')),
                ('slug', models.SlugField(blank=True, default='')),
                ('products', models.ManyToManyField(blank=True, default='', to='app.Product')),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='BestDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/best_deals/photo')),
                ('description', tinymce.models.HTMLField(default='')),
                ('products', models.ManyToManyField(blank=True, default='', to='app.Product')),
            ],
            options={
                'db_table': 'bestdeals',
            },
        ),
    ]
