from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render, get_object_or_404
from django.views.static import serve
from seller import views as sviews



urlpatterns = [    
          path("seller/signup",sviews.sellersignup,name='seller_signup'),
      url("seller/login", sviews.sellerlookup, name='seller_login'),
      url("seller/accounts/auth/", sviews.loginuser, name='seller_account_auth'),

    path('seller/', sviews.index, name='seller_index'),
    path('seller/dashboard', sviews.dashboard.as_view(), name='seller_dashboard'),
    path('seller/app', sviews.app, name='seller_app'),
    path('seller/store_setup', sviews.storesetup, name='seller_store_setup'),
    path('seller/slideshows', sviews.slideshows, name='seller_slideshows'),
    path('seller/add_product', sviews.addproduct, name='seller_add_product'),

    path('seller/my/order/<str:orderid>', sviews.myorder, name='seller_my_order'),
    path('seller/download_order/<str:orderid>', sviews.downloadorder, name='seller_download_order'),
    path('seller/remove_order/<str:orderid>', sviews.remove_order, name='seller_remove_order'),
    path('seller/overview', sviews.overview, name='seller_overview'),
    path('seller/checkout', sviews.checkout, name='seller_checkout'),
    path('seller/orders/<str:filters>', sviews.orders, name='seller_orders'),
    path('seller/order/<str:orderid>', sviews.order, name='seller_order'),
    path('seller/orders_page', sviews.orderspage, name='seller_orders_page'),
    path('seller/action/product_image/<str:productid>', sviews.addproductimage, name='seller_add_product_image'),
    path('seller/action/product_variation/<str:productid>', sviews.addproductvariation, name='seller_add_product_variation'),
    path('seller/product_overview/<str:productid>', sviews.product_overview, name='seller_product_overview'),
    path('seller/product/<str:productid>/<str:variationid>', sviews.editproductvariation, name='seller_edit_product_variation'),
    path('seller/product/<str:productid>/edit', sviews.editproduct, name='seller_edit_product'),
    path('seller/product/<str:productid>/information/edit', sviews.editproductinformation, name='seller_edit_product_information'),
    path('seller/product_variations/<str:productid>', sviews.product_variations, name='seller_product_variations'),
    path('seller/products', sviews.products, name='seller_products'),
    path('seller/product/<str:productid>', sviews.product, name='seller_product'),
    path('seller/product_information/<str:productid>', sviews.product_information, name='seller_product_information'),
    path('seller/product_images/<str:productid>', sviews.product_images, name='seller_product_images'),
    path('seller/products_page', sviews.productspage, name='seller_products_page'),
    path('seller/error_500', sviews.error500page, name='seller_error_500'),
    path('seller/error_404', sviews.error404page, name='seller_error_404'),
    path('seller/monthly_graph', sviews.monthlysalesgraph, name='seller_monthly_graph'),
    path('seller/product_monthly_graph/<str:productid>', sviews.productmonthlysalesgraph, name='seller_product_monthly_graph'),
    path('seller/carted_product/<str:id>', sviews.cartedproduct, name='seller_carted_product'),
    path('seller/new_products', sviews.newproducts, name='seller_new_products'),
    path('seller/pay_on_delivery/<str:orderid>', sviews.payondelivery, name='seller_pay_on_delivery'),
    path('seller/remove_from_cart/<str:id>', sviews.remove_from_cart, name='seller_remove_carted_product'),
    path('seller/home_group/<str:id>', sviews.homegroupproducts, name='seller_home_group_products'),
    path('seller/flashsale/all/products/<str:id>', sviews.allflashsaleproducts, name='all_seller_flash_sales_products'),
    path('seller/flash_sales_products/<str:id>', sviews.flashsaleproducts, name='seller_flash_sales_products'),
    path('seller/flashsale/<str:id>', sviews.flashsalespage, name='seller_flash_sales_page'),
    path('seller/brand/<str:slug>', sviews.brandpage, name='seller_brand_page'),
    path('seller/brand/products/<str:slug>', sviews.brandproducts, name='seller_brand_products'),
    path('seller/slideshow/<str:slug>', sviews.slideshowpage, name='seller_slideshow_page'),
    path('seller/slideshow/products/<str:slug>', sviews.slideshowproducts, name='seller_slideshow_products'),
    path('seller/flash_sales_product/<str:id>', sviews.flashsaleproduct, name='seller_flash_sales_product'),
    path('seller/product/<str:id>', sviews.product, name='seller_product'),
    path('seller/product_details/<str:productid>', sviews.product_details, name='seller_product_details'),
    path('seller/order_details/<str:orderid>', sviews.order_details, name='seller_order_details'),
    path('seller/add_to_cart/<str:productid>', sviews.add_to_cart, name='seller_add_to_cart'),
    path('seller/add_variation_to_cart/', sviews.add_variation_to_cart, name='seller_add_variation_to_cart'),
    path('seller/settings/', sviews.settings, name='seller_settings'),
    path('seller/store_information/', sviews.store_information, name='seller_store_information'),
    path('seller/store_branding/', sviews.store_branding, name='seller_store_branding'),
    path('seller/store_payment/', sviews.store_payment, name='seller_store_payment'),
    path('seller/edit/store_branding/', sviews.editstorebranding, name='seller_edit_store_branding'),
    path('seller/edit/store_information/', sviews.editstoreinformation, name='seller_edit_store_information'),
    path('seller/edit/store_payment/', sviews.editstorepayment, name='seller_edit_store_payment'),
    path('seller/store_socials/', sviews.store_socials, name='seller_store_socials'),
    path('seller/store_measurement_units/', sviews.store_measurement_units, name='seller_store_measurement_units'),
    path('seller/add_store_social_link/', sviews.addsocialink, name='seller_add_store_social_link'),
    path('seller/add_measurement_unit/', sviews.addmeasurementunit, name='seller_add_measurement_unit'),
    path('seller/similiar_products/<str:productid>', sviews.similarproducts, name='seller_similar_products'),
    path('seller/add_to_saved/<str:productid>', sviews.add_to_saved, name='seller_add_to_saved'),
    path('seller/remove_from_saved/<str:productid>', sviews.remove_from_saved, name='seller_remove_from_saved'),
    path('seller/category/<str:name>', sviews.categorys, name='seller_our_offers'),
    path('seller/offer_products/<str:name>', sviews.categoryproducts, name='seller_offer_products'),
    path('seller/category/<str:name>', sviews.categorys, name='seller_our_categorys'),
    path('seller/group/<str:slug>', sviews.homegroup, name='seller_home_group'),
    path('seller/group/products/<str:slug>', sviews.allhomegroupproducts, name='all_seller_home_group_products'),
    path('seller/group/all/', sviews.allhomegroupsection, name='all_seller_home_group_sections'),
    path('seller/newsletter/subscribe/', sviews.newlettersubscription, name='seller_news_letter_subscription'),
    path('seller/brand/<str:name>', sviews.categorys, name='seller_brands'),
    path('seller/category_products/<str:name>', sviews.categoryproducts, name='seller_category_products'),
    path('seller/update_cart/', sviews.update_cart, name='seller_update_cart'),
    path('seller/cart_count/', sviews.cart_count, name='seller_cart_count'),
    path('seller/products/all', sviews.allproducts, name='seller_all_products'),
    path('seller/products/page/all', sviews.allproductspage, name='seller_all_products_page'),
    path('seller/products/paginated', sviews.paginatedproducts, name='seller_paginated_products'),
    path('seller/products_you_may_like/', sviews.products_you_may_like, name='seller_products_you_may_like'),
    path('seller/saved_items/', sviews.saveditemspage, name='seller_saved_items_page'),
    path('seller/saved_items/products', sviews.savedproducts, name='seller_saved_items_products'),
    path('seller/search/', sviews.search_products, name='seller_search_products'),
    path('seller/place_order/', sviews.place_order, name='seller_place_order'),
    path('seller/my_orders/', sviews.myorders, name='seller_my_orders'),

    path('seller/cart/', sviews.cart, name='seller_cart'),
    path('seller/update_contact_details/', sviews.updatecontactdetails, name='seller_update_contact_details'),
    path('seller/order_paid', sviews.orderpaid, name='seller_order_paid'),
    path('seller/verify_payment', sviews.verifypayment, name='seller_verify_payment'),
    url("seller/logout", sviews.logoutuser, name='seller_account_logout'),

    # url(r'^account_activation_sent/$', gviews.account_activation_sent,
    #     name='seller_account_activation_sent'),
    # url(r'^accounts/', include('allauth.urls')),
    # url('activate-account', gviews.activate, name='seller_activate_account'),
    # url('createwallet', gviews.createaccounts, name='seller_create_accounts'),
    # url('resendactivationcode', gviews.resendactivationcode,
    #     name='seller_resend_activation_code'),
    # url('unsuspend', gviews.unsuspend, name='seller_unsuspend'),
    path('seller/select_account_type/', sviews.select_account_type, name='seller_select_account_type'),
    path('seller/confirmemail', sviews.confirmemail, name='seller_confirm_email'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
