from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render, get_object_or_404
from django.views.static import serve
from store_admin import views as adviews




urlpatterns = [    
          path("admin/signup",adviews.adminsignup,name='admin_signup'),
      url("admin/login", adviews.adminlookup, name='admin_login'),
      url("admin/accounts/auth/", adviews.loginuser, name='admin_account_auth'),

    path('admin/', adviews.index, name='admin_index'),
    path('admin/dashboard', adviews.dashboard.as_view(), name='admin_dashboard'),
    path('admin/app', adviews.app, name='admin_app'),
    path('admin/flashsales', adviews.flashsales, name='admin_flash_sales'),
    path('admin/add_flash_sales_products/<int:id>', adviews.addflashsalesproducts, name='admin_add_flash_sales_products'),
    path('admin/edit_flash_sales/<int:id>', adviews.editflashsales, name='admin_edit_flash_sales'),
    path('admin/add_category/', adviews.addcategory, name='admin_add_category'),
    path('admin/categories', adviews.categories, name='admin_categories'),
    path('admin/add_tag/', adviews.addtag, name='admin_add_tag'),

    path('admin/tags', adviews.tags, name='admin_tags'),
    path('admin/store_setup', adviews.storesetup, name='admin_store_setup'),
    path('admin/slideshows', adviews.slideshows, name='admin_slideshows'),
    path('admin/add_product', adviews.addproduct, name='admin_add_product'),

    path('admin/my/order/<str:orderid>', adviews.myorder, name='admin_my_order'),
    path('admin/download_order/<str:orderid>', adviews.downloadorder, name='admin_download_order'),
    path('admin/remove_order/<str:orderid>', adviews.remove_order, name='admin_remove_order'),
    path('admin/overview', adviews.overview, name='admin_overview'),
    path('admin/checkout', adviews.checkout, name='admin_checkout'),
    path('admin/stores/<str:filter>', adviews.stores, name='admin_stores'),
    path('admin/store/<str:storeid>', adviews.store, name='admin_store'),
    path('admin/store/approve/<str:storeid>', adviews.approvestore, name='admin_approve_store'),
    path('admin/store/details/<str:storeid>', adviews.storedetails, name='admin_store_details'),
    path('admin/order/<str:orderid>', adviews.order, name='admin_order'),
    path('admin/orders_page', adviews.orderspage, name='admin_orders_page'),
    path('admin/action/product_image/<str:productid>', adviews.addproductimage, name='admin_add_product_image'),
    path('admin/action/product_variation/<str:productid>', adviews.addproductvariation, name='admin_add_product_variation'),
    path('admin/product_overview/<str:productid>', adviews.product_overview, name='admin_product_overview'),
    path('admin/product/<str:productid>/<str:variationid>', adviews.editproductvariation, name='admin_edit_product_variation'),
    path('admin/product/<str:productid>/edit', adviews.editproduct, name='admin_edit_product'),
    path('admin/product/<str:productid>/information/edit', adviews.editproductinformation, name='admin_edit_product_information'),
    path('admin/product_variations/<str:productid>', adviews.product_variations, name='admin_product_variations'),
    path('admin/products', adviews.products, name='admin_products'),
    path('admin/product/<str:productid>', adviews.product, name='admin_product'),
    path('admin/product_information/<str:productid>', adviews.product_information, name='admin_product_information'),
    path('admin/product_images/<str:productid>', adviews.product_images, name='admin_product_images'),
    path('admin/products_page', adviews.productspage, name='admin_products_page'),
    path('admin/error_500', adviews.error500page, name='admin_error_500'),
    path('admin/error_404', adviews.error404page, name='admin_error_404'),
    path('admin/monthly_graph', adviews.monthlysalesgraph, name='admin_monthly_graph'),
    path('admin/product_monthly_graph/<str:productid>', adviews.productmonthlysalesgraph, name='admin_product_monthly_graph'),
    path('admin/carted_product/<str:id>', adviews.cartedproduct, name='admin_carted_product'),
    path('admin/new_products', adviews.newproducts, name='admin_new_products'),
    path('admin/pay_on_delivery/<str:orderid>', adviews.payondelivery, name='admin_pay_on_delivery'),
    path('admin/remove_from_cart/<str:id>', adviews.remove_from_cart, name='admin_remove_carted_product'),
    path('admin/home_group/<str:id>', adviews.homegroupproducts, name='admin_home_group_products'),
    path('admin/home_groups_page', adviews.homegroupspage, name='admin_homegroups_page'),
      path('admin/add_slideshow/', adviews.addslideshow, name='admin_add_slideshow'),
      path('admin/slideshow/<str:slug>', adviews.slideshowdetails, name='admin_slideshow_details'),
    path('admin/add_slideshow_products/<int:id>', adviews.addslideshowproducts, name='admin_add_slideshow_products'),

    path('admin/slideshows_page', adviews.slideshowspage, name='admin_slideshows_page'),
    path('admin/flashsale/all/products/<str:id>', adviews.allflashsaleproducts, name='all_admin_flash_sales_products'),
    path('admin/flash_sales_products/<str:id>', adviews.flashsaleproducts, name='admin_flash_sales_products'),
    path('admin/flashsale/<str:id>', adviews.flashsalespage, name='admin_flash_sales_page'),
    path('admin/brand/<str:slug>', adviews.brandpage, name='admin_brand_page'),
    path('admin/brand/products/<str:slug>', adviews.brandproducts, name='admin_brand_products'),
    path('admin/slideshow/<str:slug>', adviews.slideshowpage, name='admin_slideshow_page'),
    path('admin/slideshow/products/<str:slug>', adviews.slideshowproducts, name='admin_slideshow_products'),
    path('admin/flash_sales_product/<str:id>', adviews.flashsaleproduct, name='admin_flash_sales_product'),
    path('admin/product/<str:id>', adviews.product, name='admin_product'),
    path('admin/product_details/<str:productid>', adviews.product_details, name='admin_product_details'),
    path('admin/order_details/<str:orderid>', adviews.order_details, name='admin_order_details'),
    path('admin/add_to_cart/<str:productid>', adviews.add_to_cart, name='admin_add_to_cart'),
    path('admin/add_variation_to_cart/', adviews.add_variation_to_cart, name='admin_add_variation_to_cart'),
    path('admin/settings/', adviews.settings, name='admin_settings'),
    path('admin/store_information/', adviews.store_information, name='admin_store_information'),
    path('admin/store_branding/', adviews.store_branding, name='admin_store_branding'),
    path('admin/store_payment/', adviews.store_payment, name='admin_store_payment'),
    path('admin/edit/store_branding/', adviews.editstorebranding, name='admin_edit_store_branding'),
    path('admin/edit/store_information/', adviews.editstoreinformation, name='admin_edit_store_information'),
    path('admin/edit/store_payment/', adviews.editstorepayment, name='admin_edit_store_payment'),
    path('admin/store_socials/', adviews.store_socials, name='admin_store_socials'),
    path('admin/store_measurement_units/', adviews.store_measurement_units, name='admin_store_measurement_units'),
    path('admin/add_store_social_link/', adviews.addsocialink, name='admin_add_store_social_link'),
    path('admin/add_homegroup/', adviews.addhomegroup, name='admin_add_homegroup'),
    path('admin/add_homegroup_products/<int:id>', adviews.addhomegroupproducts, name='admin_add_homegroup_products'),
      path('admin/homegroup/<str:slug>', adviews.homegroupdetails, name='admin_homegroup_details'),

    path('admin/add_measurement_unit/', adviews.addmeasurementunit, name='admin_add_measurement_unit'),
    path('admin/similiar_products/<str:productid>', adviews.similarproducts, name='admin_similar_products'),
    path('admin/add_to_saved/<str:productid>', adviews.add_to_saved, name='admin_add_to_saved'),
    path('admin/remove_from_saved/<str:productid>', adviews.remove_from_saved, name='admin_remove_from_saved'),
    path('admin/category/<str:name>', adviews.categorys, name='admin_our_offers'),
    path('admin/offer_products/<str:name>', adviews.categoryproducts, name='admin_offer_products'),
    path('admin/category/<str:name>', adviews.categorys, name='admin_our_categorys'),
    path('admin/group/<str:slug>', adviews.homegroupdetails, name='admin_home_group'),
    path('admin/group/products/<str:slug>', adviews.allhomegroupproducts, name='all_admin_home_group_products'),
    path('admin/group/all/', adviews.allhomegroupsection, name='all_admin_home_group_sections'),
    path('admin/newsletter/subscribe/', adviews.newlettersubscription, name='admin_news_letter_subscription'),
    path('admin/brand/<str:name>', adviews.categorys, name='admin_brands'),
    path('admin/category_products/<str:name>', adviews.categoryproducts, name='admin_category_products'),
    path('admin/update_cart/', adviews.update_cart, name='admin_update_cart'),
    path('admin/cart_count/', adviews.cart_count, name='admin_cart_count'),
    path('admin/products/all', adviews.allproducts, name='admin_all_products'),
    path('admin/products/page/all', adviews.allproductspage, name='admin_all_products_page'),
    path('admin/products/paginated', adviews.paginatedproducts, name='admin_paginated_products'),
    path('admin/products_you_may_like/', adviews.products_you_may_like, name='admin_products_you_may_like'),
    path('admin/saved_items/', adviews.saveditemspage, name='admin_saved_items_page'),
    path('admin/saved_items/products', adviews.savedproducts, name='admin_saved_items_products'),
    path('admin/search/', adviews.search_products, name='admin_search_products'),
    path('admin/place_order/', adviews.place_order, name='admin_place_order'),
    path('admin/my_orders/', adviews.myorders, name='admin_my_orders'),
    path('admin/orders/<str:filters>', adviews.orders, name='admin_orders'),

    path('admin/cart/', adviews.cart, name='admin_cart'),
    path('admin/update_contact_details/', adviews.updatecontactdetails, name='admin_update_contact_details'),
    path('admin/order_paid', adviews.orderpaid, name='admin_order_paid'),
    path('admin/verify_payment', adviews.verifypayment, name='admin_verify_payment'),
    url("admin/logout", adviews.logoutuser, name='admin_logout'),

    # url(r'^account_activation_sent/$', gviews.account_activation_sent,
    #     name='admin_account_activation_sent'),
    # url(r'^accounts/', include('allauth.urls')),
    # url('activate-account', gviews.activate, name='admin_activate_account'),
    # url('createwallet', gviews.createaccounts, name='admin_create_accounts'),
    # url('resendactivationcode', gviews.resendactivationcode,
    #     name='admin_resend_activation_code'),
    # url('unsuspend', gviews.unsuspend, name='admin_unsuspend'),
    path('admin/select_account_type/', adviews.select_account_type, name='admin_select_account_type'),
    path('admin/confirmemail', adviews.confirmemail, name='admin_confirm_email'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
