from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render, get_object_or_404
from django.views.static import serve
from admin import views as aviews
from general import views as gviews



urlpatterns = [    
          path("signup",aviews.adminsignup,name='account_signup'),
      url("login", aviews.adminlookup, name='login'),
          url("new/accounts/signup", aviews.signup, name='new_account_signup'),
      url("accounts/auth/", aviews.loginuser, name='account_auth'),

    path('', aviews.index, name='admin_index'),
    path('dashboard', aviews.dashboard.as_view(), name='admin_dashboard'),
    path('app', aviews.app, name='admin_app'),
    path('store_setup', aviews.storesetup, name='admin_store_setup'),
    path('slideshows', aviews.slideshows, name='admin_slideshows'),
    path('add_product', aviews.addproduct, name='admin_add_product'),

    path('my/order/<str:orderid>', aviews.myorder, name='admin_my_order'),
    path('download_order/<str:orderid>', aviews.downloadorder, name='admin_download_order'),
    path('remove_order/<str:orderid>', aviews.remove_order, name='admin_remove_order'),
    path('overview', aviews.overview, name='admin_overview'),
    path('checkout', aviews.checkout, name='admin_checkout'),
    path('orders/<str:filter>', aviews.orders, name='admin_orders'),
    path('order/<str:orderid>', aviews.order, name='admin_order'),
    path('orders_page', aviews.orderspage, name='admin_orders_page'),
    path('action/product_image/<str:productid>', aviews.addproductimage, name='admin_add_product_image'),
    path('action/product_variation/<str:productid>', aviews.addproductvariation, name='admin_add_product_variation'),
    path('product_overview/<str:productid>', aviews.product_overview, name='admin_product_overview'),
    path('product/<str:productid>/<str:variationid>', aviews.editproductvariation, name='admin_edit_product_variation'),
    path('product/<str:productid>/edit', aviews.editproduct, name='admin_edit_product'),
    path('product/<str:productid>/information/edit', aviews.editproductinformation, name='admin_edit_product_information'),
    path('product_variations/<str:productid>', aviews.product_variations, name='admin_product_variations'),
    path('products', aviews.products, name='admin_products'),
    path('product/<str:productid>', aviews.product, name='admin_product'),
    path('product_information/<str:productid>', aviews.product_information, name='admin_product_information'),
    path('product_images/<str:productid>', aviews.product_images, name='admin_product_images'),
    path('products_page', aviews.productspage, name='admin_products_page'),
    path('error_500', aviews.error500page, name='admin_error_500'),
    path('error_404', aviews.error404page, name='admin_error_404'),
    path('monthly_graph', aviews.monthlysalesgraph, name='admin_monthly_graph'),
    path('product_monthly_graph/<str:productid>', aviews.productmonthlysalesgraph, name='admin_product_monthly_graph'),
    path('carted_product/<str:id>', aviews.cartedproduct, name='admin_carted_product'),
    path('new_products', aviews.newproducts, name='admin_new_products'),
    path('pay_on_delivery/<str:orderid>', aviews.payondelivery, name='admin_pay_on_delivery'),
    path('remove_from_cart/<str:id>', aviews.remove_from_cart, name='admin_remove_carted_product'),
    path('home_group/<str:id>', aviews.homegroupproducts, name='admin_home_group_products'),
    path('flashsale/all/products/<str:id>', aviews.allflashsaleproducts, name='all_admin_flash_sales_products'),
    path('flash_sales_products/<str:id>', aviews.flashsaleproducts, name='admin_flash_sales_products'),
    path('flashsale/<str:id>', aviews.flashsalespage, name='admin_flash_sales_page'),
    path('brand/<str:slug>', aviews.brandpage, name='admin_brand_page'),
    path('brand/products/<str:slug>', aviews.brandproducts, name='admin_brand_products'),
    path('slideshow/<str:slug>', aviews.slideshowpage, name='admin_slideshow_page'),
    path('slideshow/products/<str:slug>', aviews.slideshowproducts, name='admin_slideshow_products'),
    path('flash_sales_product/<str:id>', aviews.flashsaleproduct, name='admin_flash_sales_product'),
    path('product/<str:id>', aviews.product, name='admin_product'),
    path('product_details/<str:productid>', aviews.product_details, name='admin_product_details'),
    path('order_details/<str:orderid>', aviews.order_details, name='admin_order_details'),
    path('add_to_cart/<str:productid>', aviews.add_to_cart, name='admin_add_to_cart'),
    path('add_variation_to_cart/', aviews.add_variation_to_cart, name='admin_add_variation_to_cart'),
    path('settings/', aviews.settings, name='admin_settings'),
    path('store_information/', aviews.store_information, name='admin_store_information'),
    path('store_branding/', aviews.store_branding, name='admin_store_branding'),
    path('store_payment/', aviews.store_payment, name='admin_store_payment'),
    path('edit/store_branding/', aviews.editstorebranding, name='admin_edit_store_branding'),
    path('edit/store_information/', aviews.editstoreinformation, name='admin_edit_store_information'),
    path('edit/store_payment/', aviews.editstorepayment, name='admin_edit_store_payment'),
    path('store_socials/', aviews.store_socials, name='admin_store_socials'),
    path('store_measurement_units/', aviews.store_measurement_units, name='admin_store_measurement_units'),
    path('add_store_social_link/', aviews.addsocialink, name='admin_add_store_social_link'),
    path('add_measurement_unit/', aviews.addmeasurementunit, name='admin_add_measurement_unit'),
    path('similiar_products/<str:productid>', aviews.similarproducts, name='admin_similar_products'),
    path('add_to_saved/<str:productid>', aviews.add_to_saved, name='admin_add_to_saved'),
    path('remove_from_saved/<str:productid>', aviews.remove_from_saved, name='admin_remove_from_saved'),
    path('category/<str:name>', aviews.categorys, name='admin_our_offers'),
    path('offer_products/<str:name>', aviews.categoryproducts, name='admin_offer_products'),
    path('category/<str:name>', aviews.categorys, name='admin_our_categorys'),
    path('group/<str:slug>', aviews.homegroup, name='admin_home_group'),
    path('group/products/<str:slug>', aviews.allhomegroupproducts, name='all_admin_home_group_products'),
    path('group/all/', aviews.allhomegroupsection, name='all_admin_home_group_sections'),
    path('newsletter/subscribe/', aviews.newlettersubscription, name='admin_news_letter_subscription'),
    path('brand/<str:name>', aviews.categorys, name='admin_brands'),
    path('category_products/<str:name>', aviews.categoryproducts, name='admin_category_products'),
    path('update_cart/', aviews.update_cart, name='admin_update_cart'),
    path('cart_count/', aviews.cart_count, name='admin_cart_count'),
    path('products/all', aviews.allproducts, name='admin_all_products'),
    path('products/page/all', aviews.allproductspage, name='admin_all_products_page'),
    path('products/paginated', aviews.paginatedproducts, name='admin_paginated_products'),
    path('products_you_may_like/', aviews.products_you_may_like, name='admin_products_you_may_like'),
    path('saved_items/', aviews.saveditemspage, name='admin_saved_items_page'),
    path('saved_items/products', aviews.savedproducts, name='admin_saved_items_products'),
    path('search/', aviews.search_products, name='admin_search_products'),
    path('place_order/', aviews.place_order, name='admin_place_order'),
    path('my_orders/', aviews.myorders, name='admin_my_orders'),

    path('cart/', aviews.cart, name='admin_cart'),
    path('update_contact_details/', aviews.updatecontactdetails, name='admin_update_contact_details'),
    path('order_paid', aviews.orderpaid, name='admin_order_paid'),
    path('verify_payment', aviews.verifypayment, name='admin_verify_payment'),
    path("accounts/signup/", gviews.signup, name='admin_account_signup'),
    url("accounts/login/", gviews.loginuser, name='admin_account_login'),
    url("logout", aviews.logoutuser, name='admin_account_logout'),

    url(r'^account_activation_sent/$', gviews.account_activation_sent,
        name='admin_account_activation_sent'),
    url(r'^accounts/', include('allauth.urls')),
    url('activate-account', gviews.activate, name='admin_activate_account'),
    url('createwallet', gviews.createaccounts, name='admin_create_accounts'),
    url('resendactivationcode', gviews.resendactivationcode,
        name='admin_resend_activation_code'),
    url('unsuspend', gviews.unsuspend, name='admin_unsuspend'),
    path('select_account_type/', aviews.select_account_type, name='admin_select_account_type'),
    path('confirmemail', aviews.confirmemail, name='admin_confirm_email'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
